### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by sven4247** [sven4247/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by DimaLH** [comment]
Я получил Премию Киото и Премию Тьюринга за работу над парадигмой объектно-ориентированного программирования. Я был одним из первопроходцев в области персональных компьютеров и графического интерфейса. Я разработал Smalltalk — один из первых самых влиятельных языков программирования всех времен.

**Comment by sven4247** [comment]
👍
