### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by sven4247** [sven4247/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by DimaLH** [comment]
Осенью 1968 года, встретил Сеймура Паперти и некоторое время работал вместе с ним в лабораториях искусственного интеллекта в Массачусетском технологическом и Стэнфордском университетах. Это привело его к изучению работ Жана Пиаже, Жерома Брюнер, Льва Выготского, а также теории конструкционизма в обучении. Параллельно Кей начинает разрабатывать программное обеспечение для компьютера Flex, он по сути стал прототипом персонального компьютера.

В 1969 году Кей защитил диссертацию, в которой разработал принципы создания персонального компьютера - мощного, но простого в управлении.

в 1971 году перешел в исследовательский центр фирмы Xerox в Пало-Альто (Palo Alto Research Center), где продолжил теоретическую разработку прототипа персонального компьютера, названного им Dynabook.

В 1972 году становится руководителем группы перспективных исследований (Learning Research Group) в Xerox Palo Alto Research Center.

В 1982 году Кей перешел из Xerox в компанию Atari, а в 1984 году затем стал членом научного совета компании Apple.

В 1996 году Кей ушел из Apple в компанию Walt Disney. Параллельно с этим он участвовал в экспериментальном образовательном проекте The Viviarium.

в 2001 он основал исследовательский Институт Вьюпоинта

С 2006 года разрабатывает систему STEPS (STEPS Toward Expressive Programming Systems) на гранты National Science Foundatio

**Comment by sven4247** [comment]
👍
