### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by sven4247** [sven4247/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by DimaLH** [comment]
Сын маминой подруги 

С самого начала считалось, что Smalltalk как инструмент программирования Dynabook будет совсем простым, доступным для детей. Его первая версия была смоделирована несколькими тысячами операторов на Basic в октябре 1972, через четыре месяца появилась версия на языке ассемблера (Smalltalk-72). В 1974, когда её установили на Alto, можно было начинать экспериментальную работу с детьми. До 1980 работы по Smalltalk-72, а затем и Smalltalk-74 носили исключительно локальный характер. Версию Smalltalk-80 решено было сделать публичной, для чего предполагалось выпустить несколько типов документов, от статей до книг (последовательно “Синяя”, “Оранжевая” и “Зеленая”). В этой работе значительную роль сыграл Дан Ингаллс (Dan Ingalls).

**Comment by sven4247** [comment]
👍
